name: Start Project

on:
    pull_request:
    push:
      branches: [main]

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  creates-valid-project:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            # Allows us to use the same env config used locally by mapping to port to
            # the test runner container.
            - 5432:5432

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Dependencies
        run: |
          sudo apt-get update

          # Project System Dependencies
          sudo apt-get install -y \
            build-essential \
            libffi-dev \
            libpq-dev

      - name: Set up Python
        run: uv python install 3.14

      - name: Create test project
        # tp is used as prettier will reformat files if the name is too long, 
        # causing the test to fail as the generated project won't match the expected 
        # output.
        run: |
          cat <<EOF > answers.yml
          user_name: Ackama
          user_email: ackama@example.com
          project_name: Test Project
          project_module: tp
          use_feature_toggles: true
          ts_integration: true
          use_htmx: true
          EOF
          uvx copier copy . --data-file answers.yml -f tp

      - name: Install test project
        run: |
          cd tp
          uvx invoke install

      - name: Check test project is valid
        run: |
          cd tp
          cp example.env .env
          uvx invoke check
